name: tests

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - composer.json
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
      - composer.json

env:
  COMPOSER_ROOT_VERSION: 1.99

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2, 8.5]

        dependencies:
          - "highest"

    name: P${{ matrix.php-version }} - ${{ matrix.dependencies }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: xdebug
          ini-values: zend.assertions=1

      - name: Get composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --no-interaction --no-progress --prefer-lowest

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress

      - name: Run tests
        timeout-minutes: 3
        run: vendor/bin/phpunit
